---
- 网络:
    - ikuai:
        icon: router.svg
        href: https://ikuai.home.bone6.com
        description: 主路由 iKuai
    - clash:
        # icon: clash.svg
        href: https://clash.home.bone6.com/ui
        description: Clash Meta
    - incus:
        # icon: incus.svg
        href: https://incus.home.bone6.com
        description: Incus
