---
- 网络:
    - ikuai:
        icon: librespeed.svg
        href: https://ikuai.home.bone6.com
        description: 主路由 iKuai
        widget:
            type: ikuai
            url: https://ikuai.home.bone6.com
    - clash:
        icon: librespeed.svg
        href: https://clash.home.bone6.com/ui
        description: Clash Meta
    - incus:
        icon: librespeed.svg
        href: https://incus.home.bone6.com
        description: Incus
