services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/
    labels:
      caddy: caddy.bone6.com
      homepage.group: 网络
      homepage.widget.url: https://caddy.bone6.com

  rclone:
    container_name: rclone
    extends:
      file: ../../services/rclone.yml
      service: rclone
    command: sync /source/volumes/ onedrive:/rclone-volumes-backup/public/ --local-no-check-updated --ignore-size --ignore-checksum
    volumes:
      - ../../volumes:/source/volumes:ro
    
  vaultwarden:
    container_name: vaultwarden
    extends:
      file: ../../services/vaultwarden.yml
      service: vaultwarden
    labels:
      caddy: password.bone6.com pw.bone6.com
      homepage.group: 工具
      homepage.href: https://pw.bone6.com

  one-api-db:
    container_name: one-api-db
    extends:
      file: ../../services/database.yml
      service: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: one-api
    volumes:
      - ../../volumes/one-api/db:/var/lib/mysql
  
  one-api:
    container_name: one-api
    extends:
      file: ../../services/chat.yml
      service: one-api
    labels:
      caddy: one-api.bone6.com
      homepage.group: 智能
      homepage.href: https://one-api.bone6.com

  portkeyai:
    container_name: portkeyai
    extends:
      file: ../../services/chat.yml
      service: portkeyai
    labels:
      caddy: llm-api.bone6.com
      homepage.group: 智能
      homepage.href: https://llm-api.bone6.com
  
  lobe-chat-db:
    container_name: lobe-chat-db
    extends:
      file: ../../services/database.yml
      service: pgvector
    volumes:
      - ../../volumes/lobe/db/pgdata:/var/lib/postgresql/data

  lobe-chat:
    container_name: lobe-chat
    extends:
      file: ../../services/chat.yml
      service: lobe-chat
    environment:
      APP_URL: https://lobe.bone6.com
    links:
      - lobe-chat-db:postgres
    labels:
      caddy: lobe.bone6.com chat.bone6.com
      homepage.group: 智能
      homepage.href: https://lobe.bone6.com
  
  n8n-db:
    container_name: n8n-db
    extends:
      file: ../../services/database.yml
      service: postgres
    environment:
      POSTGRES_DB: zeabur
    volumes:
      - ../../volumes/n8n/db/pgdata:/var/lib/postgresql/data
  
  n8n:
    container_name: n8n
    extends:
      file: ../../services/n8n.yml
      service: n8n
    links:
      - n8n-db:postgres
    labels:
      caddy: n8n.bone6.com
      homepage.group: 工具
      homepage.icon: https://n8n.bone6.com/favicon.ico
      homepage.href: https://n8n.bone6.com

  # langflow-db:
  #   container_name: langflow-db
  #   extends:
  #     file: ../../services/database.yml
  #     service: postgres
  #   environment:
  #     POSTGRES_USER: langflow
  #     POSTGRES_PASSWORD: langflow
  #     POSTGRES_DB: langflow
  #   volumes:
  #     - ../../volumes/langflow/db:/var/lib/postgresql/data
  
  # langflow:
  #   container_name: langflow
  #   extends:
  #     file: ../../services/langflow.yml
  #     service: langflow
  #   links:
  #     - langflow-db:postgres
  #   labels:
  #     caddy: flow.bone6.com
  #     homepage.group: 智能
  #     homepage.icon: https://flow.bone6.com/favicon.ico
  #     homepage.href: https://flow.bone6.com

  # illa:
  #   container_name: illa
  #   extends:
  #     file: ../../services/illa.yml
  #     service: illa
  #   labels:
  #     caddy: illa.bone6.com
  #     homepage.group: 工具
  #     homepage.icon: https://illa.bone6.com/cloud/favicon.ico
  #     homepage.href: https://illa.bone6.com

  headscale:
    container_name: headscale
    extends:
      file: ../../services/headscale.yml
      service: server
    labels:
      caddy: headscale.bone6.com

  headscale-derper:
    container_name: headscale-derper
    extends:
      file: ../../services/headscale.yml
      service: derper
    labels:
      caddy: ghk.derp.bone6.com
  
  headscale-ui:
    container_name: headscale-ui
    extends:
      file: ../../services/headscale.yml
      service: ui
    labels:
      caddy: headscale.bone6.com
      homepage.group: 网络
      homepage.href: https://headscale.bone6.com

  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.bone6.com

  gitea-db:
    container_name: gitea-db
    extends:
      file: ../../services/database.yml
      service: postgres
    environment:
      - POSTGRES_DB=gitea
    volumes:
      - ../../volumes/gitea/postgres:/var/lib/postgresql/data
  
  gitea:
    container_name: gitea
    extends:
      file: ../../services/gitea.yml
      service: server
    depends_on:
      - gitea-db
    links:
      - gitea-db:db
    labels:
      caddy: git.bone6.com gitea.bone6.com
      homepage.group: 工具
      homepage.href: git.bone6.com

  memos:
    container_name: memos
    extends:
      file: ../../services/memos.yml
      service: memos
    labels:
      caddy: memos.bone6.com
      homepage.group: 工具
      homepage.icon: https://memos.bone6.com/apple-touch-icon.png
      homepage.href: https://memos.bone6.com

  it-tools:
    container_name: it-tools
    extends:
      file: ../../services/it-tools.yml
      service: it-tools
    labels:
      caddy: tools.bone6.com
      homepage.group: 工具
      homepage.icon: https://tools.bone6.com/favicon.ico
      homepage.href: https://tools.bone6.com

  miniflux-db:
    container_name: miniflux-db
    extends:
      file: ../../services/database.yml
      service: postgres
    environment:
      - POSTGRES_DB=miniflux
    volumes:
      - ../../volumes/miniflux/postgres:/var/lib/postgresql/data

  miniflux:
    container_name: miniflux
    extends:
      file: ../../services/rss.yml
      service: miniflux
    depends_on:
      - miniflux-db
    links:
      - miniflux-db:db
    labels:
      caddy: miniflux.bone6.com rss.bone6.com
      homepage.group: 工具
      homepage.icon: https://rss.bone6.com/icon/icon-128.png
      homepage.href: https://rss.bone6.com

  searxng:
    container_name: searxng
    extends:
      file: ../../services/searxng.yml
      service: searxng
    environment:
      - BASE_URL=https://searxng.bone6.com
    labels:
      caddy: searxng.bone6.com
      homepage.group: 工具
      homepage.icon: https://searxng.bone6.com/favicon.ico
      homepage.href: https://searxng.bone6.com
