services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/
    labels:
      caddy: caddy.bone6.top
      homepage.group: 网络
      homepage.widget.url: https://caddy.bone6.top

  rclone:
    container_name: rclone
    extends:
      file: ../../services/rclone.yml
      service: rclone
    command: sync /source/volumes/ onedrive:/rclone-backup/volumes/ --local-no-check-updated --ignore-size --ignore-checksum
    volumes:
      - ../../volumes:/source/volumes:ro
    
  vaultwarden:
    container_name: vaultwarden
    extends:
      file: ../../services/vaultwarden.yml
      service: vaultwarden
    labels:
      caddy: password.bone6.top pw.bone6.top
      homepage.group: 工具

  one-api-db:
    container_name: one-api-db
    extends:
      file: ../../services/database.yml
      service: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: one-api
    volumes:
      - ../../volumes/one-api/db:/var/lib/mysql
  
  one-api:
    container_name: one-api
    extends:
      file: ../../services/chat.yml
      service: one-api
    labels:
      caddy: one-api.bone6.top
      homepage.group: 智能

  lobe-chat:
    container_name: lobe-chat
    extends:
      file: ../../services/chat.yml
      service: lobe-chat
    labels:
      caddy: lobe.bone6.top chat.bone6.top lobe.bone6.com chat.bone6.com
      homepage.group: 智能
      homepage.href: https://lobe.bone6.com
  
  n8n-postgres:
    container_name: n8n-postgres
    extends:
      file: ../../services/database.yml
      service: postgres
    environment:
      POSTGRES_DB: zeabur
    volumes:
      - ../../volumes/n8n/db/pgdata:/var/lib/postgresql/data
  
  n8n:
    container_name: n8n
    extends:
      file: ../../services/n8n.yml
      service: n8n
    links:
      - n8n-postgres:postgres
    labels:
      caddy: n8n.bone6.top
      homepage.group: 工具
      homepage.icon: https://n8n.bone6.top/favicon.ico
      homepage.href: https://n8n.bone6.top

  illa:
    container_name: illa
    extends:
      file: ../../services/illa.yml
      service: illa
    labels:
      caddy: illa.bone6.top
      homepage.group: 工具

  headscale:
    container_name: headscale
    extends:
      file: ../../services/headscale.yml
      service: server
    labels:
      caddy: headscale.bone6.top

  headscale-derper:
    container_name: headscale-derper
    extends:
      file: ../../services/headscale.yml
      service: derper
    labels:
      caddy: ghk.derp.bone6.top
  
  headscale-ui:
    container_name: headscale-ui
    extends:
      file: ../../services/headscale.yml
      service: ui
    labels:
      caddy: headscale.bone6.top
      homepage.group: 网络
      homepage.href: https://headscale.bone6.top

  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.bone6.com

  gitea-db:
    container_name: gitea-db
    extends:
      file: ../../services/database.yml
      service: postgres
    environment:
      - POSTGRES_DB=gitea
    volumes:
      - ../../volumes/gitea/postgres:/var/lib/postgresql/data
  
  gitea:
    container_name: gitea
    extends:
      file: ../../services/gitea.yml
      service: server
    depends_on:
      - gitea-db
    links:
      - gitea-db:db
    labels:
      caddy: gitea.bone6.top git.bone6.top
      homepage.group: 工具

  memos:
    container_name: memos
    extends:
      file: ../../services/memos.yml
      service: memos
    labels:
      caddy: memos.bone6.top
      homepage.group: 工具
      homepage.icon: https://memos.bone6.top/apple-touch-icon.png
      homepage.href: https://memos.bone6.top

  it-tools:
    container_name: it-tools
    extends:
      file: ../../services/it-tools.yml
      service: it-tools
    labels:
      caddy: tools.bone6.top
      homepage.group: 工具
      homepage.icon: https://tools.bone6.top/favicon.ico
      homepage.href: https://tools.bone6.top

