version: "3.7"
services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy

  rclone:
    container_name: rclone
    extends:
      file: ../../services/rclone.yml
      service: rclone
    command: sync /source/volumes/ onedrive:/rclone-backup/volumes/ --local-no-check-updated --ignore-size --ignore-checksum
    volumes:
      - ./volumes:/source/volumes:ro
    
  vaultwarden:
    container_name: vaultwarden
    extends:
      file: ../../services/vaultwarden.yml
      service: vaultwarden
    labels:
      caddy: password.bone6.top pw.bone6.top

  one-api-db:
    extends:
      file: ../../services/chat.yml
      service: one-api-db

  one-api:
    extends:
      file: ../../services/chat.yml
      service: one-api
    labels:
      caddy: one-api.bone6.top

  lobe-chat:
    container_name: lobe-chat
    extends:
      file: ../../services/chat.yml
      service: lobe-chat
    labels:
      caddy: lobe.bone6.top
      homepage.group: 智能
      homepage.icon: https://registry.npmmirror.com/@lobehub/assets-favicons/1.4.0/files/assets/favicon.ico
      homepage.href: https://lobe.bone6.top
  
  n8n-postgres:
    container_name: n8n-postgres
    extends:
      file: ../../services/n8n.yml
      service: n8n-postgres
  
  n8n:
    container_name: n8n
    extends:
      file: ../../services/n8n.yml
      service: n8n
    links:
      - n8n-postgres:postgres
    labels:
      caddy: n8n.bone6.top

  illa:
    container_name: illa
    extends:
      file: ../../services/illa.yml
      service: illa
    labels:
      caddy: illa.bone6.top

  headscale:
    container_name: headscale
    extends:
      file: ../../services/headscale.yml
      service: server
    labels:
      caddy: headscale.bone6.top

  headscale-derper:
    container_name: headscale-derper
    extends:
      file: ../../services/headscale.yml
      service: derper
    labels:
      caddy: ghk.derp.bone6.top
  
  headscale-ui:
    container_name: headscale-ui
    extends:
      file: ../../services/headscale.yml
      service: ui
    labels:
      caddy: headscale.bone6.top
      homepage.group: 网络
      homepage.name: Headscale
      homepage.icon: https://tailscale.com/favicon.ico
      homepage.href: https://headscale.bone6.top
      homepage.description: Headscale 组网管理

  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.bone6.top
      caddy.reverse_proxy: "{{upstreams 3000}}"

  gitea-db:
    container_name: gitea-db
    extends:
      file: ../../services/gitea.yml
      service: db

  gitea:
    container_name: gitea
    extends:
      file: ../../services/gitea.yml
      service: server
    volumes:
      - ./volumes:/source/volumes:ro
    depends_on:
      - gitea-db
    links:
      - gitea-db:db
    labels:
      caddy: gitea.bone6.top
  
  memos:
    container_name: memos
    extends:
      file: ../../services/memos.yml
      service: memos
    labels:
      caddy: memos.bone6.top
      homepage.group: 工具
      homepage.icon: https://memos.bone6.top/apple-touch-icon.png
      homepage.href: https://memos.bone6.top
  


