services:
  consul-server1:
    container_name: consul-server1
    extends:
      file: ../../services/consul.yml
      service: server
    ports:
      - 8500:8500
      - 8600:8600
    volumes:
      - ../../volumes/consul/config/server1.json:/consul/config/server1.json:ro
      - ../../volumes/consul/data1:/consul/data/

  consul-server2:
    container_name: consul-server2
    extends:
      file: ../../services/consul.yml
      service: server
    volumes:
      - ../../volumes/consul/config/server2.json:/consul/config/server2.json:ro
      - ../../volumes/consul/data2:/consul/data/
  
  consul-server3:
    container_name: consul-server3
    extends:
      file: ../../services/consul.yml
      service: server
    volumes:
      - ../../volumes/consul/config/server3.json:/consul/config/server3.json:ro
      - ../../volumes/consul/data3:/consul/data/
    
  consul-client:
    extends:
      file: ../../services/consul.yml
      service: client
    container_name: consul-client
    volumes:
      - ../../volumes/consul/config/client.json:/consul/config/client.json:ro
      - ../../volumes/consul/data4:/consul/data/

  consul-registrator:
    extends:
      file: ../../services/consul.yml
      service: registrator
    container_name: consul-registrator

networks:
  consul:
    driver: bridge
