---

- 开发主页:
    - Github:
        - abbr: GH
          href: https://github.com/zrr1999
    - Gitee:
        - abbr: GT
          href: https://gitee.com/zrr1999

- 文档:
    - Homepage docs:
        - abbr: HP
          href: https://gethomepage.dev/

- 其他:
    - Simple Icon:
        - abbr: SI
          href: https://simpleicons.org
    - Dashboard Icons:
        - abbr: DI
          href: https://github.com/walkxcode/dashboard-icons
