---
title: 导航主页
language: zh-CN
base: https://homepage.bone6.com
logpath: /logs

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true
# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey