---
- resources:
    cpu: true
    memory: true
    # disk: "C://"

- datetime:
    text_size: xl
    format:
      timeStyle: short
      
- search:
    provider: [baidu, brave, google, duckduckgo]
    target: _blank

