services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    volumes:
      - ../volumes/alist:/opt/alist/data
    ports:
      - 5244:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped
    labels:
      caddy.reverse_proxy: "{{upstreams 5244}}"
