services:
  qinglong:
    image: whyour/qinglong:latest
    restart: unless-stopped
    environment:
      QlBaseUrl: '/'
    volumes:
      - ../volumes/qinglong:/ql/data
    labels:
      caddy.reverse_proxy: "{{upstreams 5700}}"
  n8n:
    image: n8nio/n8n:next
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=password
      - WEBHOOK_URL=https://n8n.sixbones.dev
    volumes:
      - ../volumes/n8n/node:/home/node/.n8n
    labels:
      caddy.reverse_proxy: "{{upstreams 5678}}"
      homepage.name: n8n
      homepage.description: 流程自动化工具。