services:
  caddy:
    image: zrr1999/zrr-caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/caddy/:/etc/caddy/
      - ../volumes/caddy/data:/data
      - ../volumes/caddy/config:/config
    env_file:
      - path: ${AUTO_TOKEN_ENV_DIR}/tencentcloud.env
        required: false
    environment:
      - ACME_AGREE=true
      - TZ=Asia/Shanghai
