services:
  caddy:
    image: zrr1999/zrr-caddy
    restart: unless-stopped
    command: "caddy docker-proxy --caddyfile-path /etc/caddy/Caddyfile"
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../volumes/caddy/data:/data
      - ../volumes/caddy/config:/config
    env_file:
      - path: ${AUTO_TOKEN_ENV_DIR}/tencentcloud.env
      - path: ${AUTO_TOKEN_ENV_DIR}/lexicon.env
        required: true
    environment:
      - ACME_AGREE=true
      - TZ=Asia/Shanghai
    labels:
      caddy.reverse_proxy: "127.0.0.1:2019"
      caddy.reverse_proxy.header_up: Host 127.0.0.1:2019
      homepage.name: Caddy
      homepage.description: Caddy Web Server
      homepage.icon: https://caddyserver.com/resources/images/favicon.png
      homepage.widget.type: caddy
      