services:
  one-api:
    image: justsong/one-api:latest
    restart: unless-stopped
    environment:
      - PORT=3000
      - SQL_DSN=oneapi:123456@tcp(one-api-db:3306)/one-api
      - TZ=Asia/Shanghai
    volumes:
      - ../volumes/one-api/data:/data
      - ../volumes/one-api/logs:/app/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: --log-dir /app/logs
    labels:
      caddy.reverse_proxy: "{{upstreams 3000}}"
      homepage.name: One API
      homepage.description: GPT 统一代理。
      homepage.icon: https://one-api.bone6.top/logo.png

  lobe-chat:
    image: lobehub/lobe-chat:latest
    restart: unless-stopped
    env_file:
      - path: ${AUTO_TOKEN_ENV_DIR}/lobechat.env
        required: false
      # - path: ${AUTO_TOKEN_ENV_DIR}/s3.env
      #   required: false
      # - path: ${AUTO_TOKEN_ENV_DIR}/clerk.env
      #   required: false
    # environment:
    #   NEXT_PUBLIC_SERVICE_MODE: server
    #   NEXT_PUBLIC_S3_DOMAIN: https://basic-1256983506.cos.ap-beijing.myqcloud.com
    #   DATABASE_URL: postgres
    container_name: lobe-chat
    labels:
      caddy.reverse_proxy: "{{upstreams 3210}}"
      homepage.name: LobeChat
      homepage.description: 开源的高性能聊天机器人框架 LobeChat。
      homepage.icon: https://registry.npmmirror.com/@lobehub/assets-favicons/1.4.0/files/assets/favicon.ico