services:
  server:
    image: gitea/gitea:1.18.5
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=password
    volumes:
      - ../volumes/gitea/data:/data
    ports:
      - "6022:22"
    labels:
      caddy.reverse_proxy: "{{upstreams 3000}}"
      homepage.name: Gitea
      homepage.description: 自部署 git 服务。
      homepage.icon: gitea.svg
