services:
  base:
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    ports:
      - 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      caddy: homepage.bone6.top
      caddy.reverse_proxy: "{{upstreams 3000}}"
