services:
  base:
    image: 'ghcr.io/benphelps/homepage:latest'
    container_name: homepage
    ports:
      - '9333:3000'
    volumes:
      - '../configs/homepage:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
