services:
  base:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    labels:
      caddy.reverse_proxy: "{{upstreams 3000}}"
