services:
  illa:
    image: illasoft/illa-builder:v4.7.0
    restart: unless-stopped
    volumes:
      - ../volumes/illa/postgresql/:/var/lib/postgresql/
    labels:
      caddy.reverse_proxy: "{{upstreams 2022}}"
      homepage.name: illa
      homepage.description: 低代码平台。
