services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.118.2
    extends:
      file: immich/hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - /media/immich:/usr/src/app/upload
    environment:
      - TZ=Asia/Shanghai
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped
    healthcheck:
      disable: false
    labels:
      caddy.reverse_proxy: "{{upstreams 2283}}"
      homepage.name: Immich
      homepage.description: 一个开源的、自托管的、AI驱动的照片管理平台。
      homepage.icon: https://github.com/immich-app/immich/raw/main/design/immich-logo-stacked-light.svg

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.118.2-openvino
    restart: unless-stopped
    extends:
      file: immich/hwaccel.ml.yml
      service: openvino
    volumes:
      - ../volumes/immich/immich-machine-learning/cache:/cache
    healthcheck:
      disable: false
