services:
  langflow:
    image: langflowai/langflow:latest
    pull_policy: always
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
    volumes:
      - ../volumes/langflow/data:/app/langflow
    labels:
      caddy.reverse_proxy: "{{upstreams 7860}}"
