services:
  portkeyai:
    image: "portkeyai/gateway:latest"
    restart: unless-stopped
    labels:
      caddy.reverse_proxy: "{{upstreams 8787}}"
      homepage.name: Portkey-AI
      homepage.description: LLM API 统一网关。
      homepage.icon: https://framerusercontent.com/images/pkFK3AGXHirogqiN67JGtlnMVM.png

  new-api:
    image: calciumion/new-api:latest
    restart: unless-stopped
    env_file:
      - path: ${AUTO_TOKEN_ENV_DIR}/new-api.env
        required: true
    environment:
      PORT: 3000
      TZ: Asia/Shanghai
      NODE_NAME: home
      ERROR_LOG_ENABLED: "true"
      BATCH_UPDATE_ENABLED: "true"
      SESSION_COOKIE_SECURE: "true"
      SESSION_COOKIE_TRUSTED_URL: https://new-api.zrr.dev
    volumes:
      - ../volumes/new-api/data:/data
      - ../volumes/new-api/logs:/app/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://localhost:3000/api/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: --log-dir /app/logs
    labels:
      caddy.reverse_proxy: "{{upstreams 3000}}"
      homepage.name: New API
      homepage.description: LLM API 统一网关。

  lobe-chat:
    image: lobehub/lobe-chat-database:latest
    restart: unless-stopped
    env_file:
      - path: ${AUTO_TOKEN_ENV_DIR}/auth0.env
        required: true
      - path: ${AUTO_TOKEN_ENV_DIR}/nextauth.env
        required: true
      - path: ${AUTO_TOKEN_ENV_DIR}/s3.env
        required: false
      - path: ${AUTO_TOKEN_ENV_DIR}/lobechat.env
        required: false
    environment:
      DATABASE_URL: ***REMOVED***?sslmode=disable
    container_name: lobe-chat
    labels:
      caddy.reverse_proxy: "{{upstreams 3210}}"
      homepage.name: LobeChat
      homepage.description: 开源的高性能聊天机器人框架 LobeChat。
      homepage.icon: https://registry.npmmirror.com/@lobehub/assets-favicons/1.4.0/files/assets/favicon.ico

  langflow:
    image: langflowai/langflow:latest
    restart: unless-stopped
    environment:
      LANGFLOW_DATABASE_URL: ***REMOVED***
    volumes:
      - ../volumes/langflow/data:/app/langflow
    labels:
      caddy.reverse_proxy: "{{upstreams 7860}}"
