services:
  memos:
    image: neosmemo/memos:0.23.1
    volumes:
      - ../volumes/memos/:/var/opt/memos
    # environment:
    #   MEMOS_DRIVER: postgres
    #   MEMOS_DSN: postgresql://root:password@postgres:5432/memos?sslmode=disable
    labels:
      caddy.reverse_proxy: "{{upstreams 5230}}"
      homepage.name: Memos
      homepage.description: 一个开源、轻量级的笔记记录服务。

