services:
  speedtest:
    image: ghcr.io/librespeed/speedtest:latest
    restart: unless-stopped
    environment:
      MODE: standalone
      TITLE: "LibreSpeed"
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:GleUCbpBA2aoczZsxTHPmZkf5Pab5GCoAQBy6iunbCI=
      - DB_CONNECTION=sqlite
    volumes:
      - ../volumes/speedtest:/config
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"
      homepage.name: Speedtest Tracker
      homepage.description: 最近网络速度
      homepage.icon: librespeed.svg
      homepage.widget.type: speedtest
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8866:8080" # webapp
      - "8867:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ../volumes/scrutiny/config:/opt/scrutiny/config
      - ../volumes/scrutiny/influxdb:/opt/scrutiny/influxdb
    labels:
      caddy.reverse_proxy: "{{upstreams 8080}}"
