services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=zeabur
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_PASSWORD=Z5jox6A72cIKbU93P1nsJFwfki0E84uH
      - WEBHOOK_URL=https://n8n.bone6.top
    ports:
      - 5678
    volumes:
      - ../volumes/n8n/node:/home/node/.n8n
    labels:
      caddy.reverse_proxy: "{{upstreams 5678}}"
      homepage.name: n8n
      homepage.description: 流程自动化工具。