services:
  qinglong:
    image: whyour/qinglong:latest
    volumes:
      - ../volumes/qinglong:/ql/data
    ports:
      - 5700
    environment:
      QlBaseUrl: '/'
    restart: unless-stopped
    labels:
      caddy.reverse_proxy: "{{upstreams 5700}}"