services:
  qinglong:
    image: whyour/qinglong:latest
    restart: unless-stopped
    environment:
      QlBaseUrl: '/'
    volumes:
      - ../volumes/qinglong:/ql/data
    labels:
      caddy.reverse_proxy: "{{upstreams 5700}}"