services:
  upsnap:
    image: seriousm4x/upsnap:4
    restart: unless-stopped
    ports:
      - 5000
    volumes:
      - ../volumes/upsnap/data:/app/pb_data
    environment:
      - TZ=Asia/Shanghai
      - UPSNAP_INTERVAL=@every 600s
      - UPSNAP_SCAN_RANGE=192.168.0.0/16
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
      - UPSNAP_WEBSITE_TITLE=UpSnap
    labels:
      caddy.reverse_proxy: "{{upstreams 5000}}"
      homepage.name: UpSnap
      homepage.description: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
      homepage.icon: https://github.com/seriousm4x/UpSnap/blob/master/frontend/static/gopher.svg
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    healthcheck:
      test: curl -fs "http://localhost:5000/api/health" || exit 1
      interval: 10s
