services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ../volumes/vaultwarden/data:/data
    ports:
      - 80
    environment:
      SIGNUPS_ALLOWED: "false"
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"
      homepage.name: vaultwarden
      homepage.description: 密码管理工具。
      homepage.icon: bitwarden.svg
