regions:
  901:
    regionid: 901
    regioncode: ghk
    regionname: Guanxing HongKong
    nodes:
      - name: 1
        regionid: 901
        hostname: ghk.derp.sixbones.dev
        stunport: 3478
        stunonly: false
        derpport: 443
