version: "3"
services:
  caddy:
    image: zrr1999/zrr-caddy
    network_mode: "host"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/.config/caddy:/root/.caddy
    restart: always
    environment:
      - DNSPOD_TOKEN=$DNSPOD_TOKEN
      - DNSPOD_ID=$DNSPOD_ID
      - ACME_AGREE=true
      - TZ=Asia/Shanghai
