services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/
    labels:
      caddy: caddy.lab.bone6.com

  rclone:
    container_name: rclone
    extends:
      file: ../../services/rclone.yml
      service: rclone
    command: sync /source/volumes/ onedrive:/rclone-volumes-backup/lab/ --exclude "cache/" --local-no-check-updated --ignore-size --ignore-checksum
    volumes:
      - ../../volumes:/source/volumes:ro

  alist:
    container_name: alist
    extends:
      file: ../../services/alist.yml
      service: alist 
    labels:
      caddy: alist.lab.bone6.com
  
  aria2:
    container_name: aria2
    extends:
      file: ../../services/alist.yml
      service: aria2 
    labels:
      caddy: rpc.aria2.lab.bone6.com
  
  ariang:
    container_name: ariang
    extends:
      file: ../../services/alist.yml
      service: ariang 
    labels:
      caddy: aria2.lab.bone6.com
  
  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.lab.bone6.com

  qinglong:
    container_name: qinglong
    extends:
      file: ../../services/qinglong.yml
      service: qinglong
    labels:
      caddy: qinglong.lab.bone6.com

  speedtest:
    container_name: speedtest
    extends:
      file: ../../services/speedtest.yml
      service: speedtest
    labels:
      caddy: speedtest.lab.bone6.com

  speedtest-tracker:
    container_name: speedtest-tracker
    extends:
      file: ../../services/speedtest.yml
      service: speedtest-tracker
    environment:
      - APP_URL=https://speedtest-tracker.lab.bone6.com
    labels:
      caddy: speedtest-tracker.lab.bone6.com
      homepage.widget.type: https://speedtest-tracker.lab.bone6.com

  scrutiny:
    container_name: scrutiny
    extends:
      file: ../../services/scrutiny.yml
      service: scrutiny
    devices:
      - "/dev/nvme0"
    labels:
      caddy: scrutiny.lab.bone6.com

  immich-db:
    container_name: immich-db
    extends:
      file: ../../services/database.yml
      service: pgvecto-rs
    environment:
      - POSTGRES_DB=immich
    volumes:
      - ../../volumes/immich/postgres:/var/lib/postgresql/data

  immich-redis:
    container_name: immich-redis
    extends:
      file: ../../services/database.yml
      service: redis

  immich-server:
    container_name: immich-server
    extends:
      file: ../../services/immich.yml
      service: immich-server
    depends_on:
      - immich-db
      - immich-redis
    links:
      - immich-db:database
      - immich-redis:redis
    environment:
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
    labels:
      caddy: immich.lab.bone6.com
      homepage.group: 家庭
      homepage.href: https://immich.lab.bone6.com

  immich-machine-learning:
    container_name: immich-machine-learning
    extends:
      file: ../../services/immich.yml
      service: immich-machine-learning
