include:
  - compose.public.yml
services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/network.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/
    labels:
      caddy: caddy.home.sixbones.dev
      homepage.group: 网络
      homepage.widget.url: https://caddy.home.sixbones.dev

  rathole:
    container_name: rathole
    extends:
      file: ../../services/network.yml
      service: rathole-client

  restic:
    container_name: restic
    extends:
      file: ../../services/storage.yml
      service: restic
    environment:
      - RESTIC_REPOSITORY=s3:$RESTIC_ENDPOINT/lab
    

  # rclone:
  #   container_name: rclone
  #   extends:
  #     file: ../../services/storage.yml
  #     service: rclone
  #   command: sync /source/volumes/ onedrive:/rclone-volumes-backup/lab/ --exclude "cache/" --local-no-check-updated --ignore-size --ignore-checksum
  #   volumes:
  #     - ../../volumes:/source/volumes:ro

  alist:
    container_name: alist
    extends:
      file: ../../services/alist.yml
      service: alist 
    labels:
      caddy: alist.home.sixbones.dev
  
  aria2:
    container_name: aria2
    extends:
      file: ../../services/downloader.yml
      service: aria2 
    labels:
      caddy: rpc.aria2.home.sixbones.dev
  
  ariang:
    container_name: ariang
    extends:
      file: ../../services/downloader.yml
      service: ariang 
    labels:
      caddy: aria2.home.sixbones.dev
  
  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.home.sixbones.dev

  qinglong:
    container_name: qinglong
    extends:
      file: ../../services/automation.yml
      service: qinglong
    labels:
      caddy: qinglong.home.sixbones.dev

  speedtest:
    container_name: speedtest
    extends:
      file: ../../services/monitor.yml
      service: speedtest
    labels:
      caddy: speedtest.home.sixbones.dev

  speedtest-tracker:
    container_name: speedtest-tracker
    extends:
      file: ../../services/monitor.yml
      service: speedtest-tracker
    environment:
      - APP_URL=https://speedtest-tracker.home.sixbones.dev
    labels:
      caddy: speedtest-tracker.home.sixbones.dev
      homepage.widget.type: https://speedtest-tracker.home.sixbones.dev

  scrutiny:
    container_name: scrutiny
    extends:
      file: ../../services/monitor.yml
      service: scrutiny
    devices:
      - "/dev/nvme0"
    labels:
      caddy: scrutiny.home.sixbones.dev

  immich-db:
    container_name: immich-db
    extends:
      file: ../../services/database.yml
      service: pgvecto-rs
    environment:
      - POSTGRES_DB=immich
    volumes:
      - ../../volumes/immich/postgres:/var/lib/postgresql/data

  immich-redis:
    container_name: immich-redis
    extends:
      file: ../../services/database.yml
      service: redis

  immich-server:
    container_name: immich-server
    extends:
      file: ../../services/immich.yml
      service: immich-server
    depends_on:
      - immich-db
      - immich-redis
    links:
      - immich-db:database
      - immich-redis:redis
    environment:
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
    labels:
      caddy: immich.home.sixbones.dev
      homepage.group: 家庭
      homepage.href: https://immich.home.sixbones.dev

  immich-machine-learning:
    container_name: immich-machine-learning
    extends:
      file: ../../services/immich.yml
      service: immich-machine-learning

  jellyfin:
    container_name: jellyfin
    extends:
      file: ../../services/media.yml
      service: jellyfin
    labels:
      caddy: jellyfin.home.sixbones.dev

  jellyseerr:
    container_name: jellyseerr
    extends:
      file: ../../services/media.yml
      service: jellyseerr
    labels:
      caddy: jellyseerr.home.sixbones.dev
  
  sonarr:
    container_name: sonarr
    extends:
      file: ../../services/media.yml
      service: sonarr
    labels:
      caddy: sonarr.home.sixbones.dev

  radarr:
    container_name: radarr
    extends:
      file: ../../services/media.yml
      service: radarr
    labels:
      caddy: radarr.home.sixbones.dev

  prowlarr:
    container_name: prowlarr
    extends:
      file: ../../services/media.yml
      service: prowlarr
    labels:
      caddy: prowlarr.home.sixbones.dev
