version: "3.7"
services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/

  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.lab.bone6.top
      caddy.reverse_proxy: "{{upstreams 3000}}"

  qinglong:
    container_name: qinglong
    extends:
      file: ../../services/qinglong.yml
      service: qinglong
    labels:
      caddy: qinglong.lab.bone6.top

  speedtest-tracker:
    container_name: speedtest-tracker
    extends:
      file: ../../services/speedtest.yml
      service: speedtest-tracker
    labels:
      caddy: speedtest.lab.bone6.top

  scrutiny:
    container_name: scrutiny
    extends:
      file: ../../services/scrutiny.yml
      service: scrutiny
    devices:
      - "/dev/nvme0"
      # - "/dev/nvme1"
    labels:
      caddy: scrutiny.lab.bone6.top
