services:
  caddy:
    container_name: caddy
    extends:
      file: ../../services/caddy.yml
      service: caddy
    volumes:
      - ./configs/caddy/:/etc/caddy/
    labels:
      caddy: caddy.home.bone6.com
      homepage.group: 网络
      homepage.widget.url: https://caddy.home.bone6.com

  rclone:
    container_name: rclone
    extends:
      file: ../../services/rclone.yml
      service: rclone
    command: sync /source/volumes/ onedrive:/rclone-volumes-backup/home/ --exclude "cache/" --local-no-check-updated --ignore-size --ignore-checksum
    volumes:
      - ../../volumes:/source/volumes:ro
    
  alist:
    container_name: alist
    extends:
      file: ../../services/alist.yml
      service: alist 
    labels:
      caddy: alist.home.bone6.com
      homepage.group: 工具
  
  aria2:
    container_name: aria2
    extends:
      file: ../../services/alist.yml
      service: aria2 
    labels:
      caddy: rpc.aria2.home.bone6.com
      homepage.group: 工具
  ariang:
    container_name: ariang
    extends:
      file: ../../services/alist.yml
      service: ariang 
    labels:
      caddy: aria2.home.bone6.com
      homepage.group: 工具

  homepage:
    container_name: homepage
    extends:
      file: ../../services/homepage.yml
      service: base
    volumes:
      - ./configs/homepage:/app/config:ro
    labels:
      caddy: homepage.home.bone6.com
  qinglong:
    container_name: qinglong
    extends:
      file: ../../services/automation.yml
      service: qinglong
    labels:
      caddy: qinglong.home.bone6.com
      homepage.group: 工具
      homepage.href: https://qinglong.home.bone6.com

  speedtest:
    container_name: speedtest
    extends:
      file: ../../services/monitor.yml
      service: speedtest
    labels:
      caddy: speedtest.home.bone6.com

  speedtest-tracker:
    container_name: speedtest-tracker
    extends:
      file: ../../services/monitor.yml
      service: speedtest-tracker
    environment:
      - APP_URL=https://speedtest-tracker.home.bone6.com
    labels:
      caddy: speedtest-tracker.home.bone6.com
      homepage.group: 工具
      homepage.href: https://speedtest-tracker.home.bone6.com
      homepage.widget.url: https://speedtest-tracker.home.bone6.com

  upsnap:
    container_name: upsnap
    extends:
      file: ../../services/upsnap.yml
      service: upsnap
    labels:
      caddy: upsnap.home.bone6.com
      homepage.group: 工具
      homepage.href: https://upsnap.home.bone6.com
      homepage.icon: https://upsnap.home.bone6.com/gopher.svg

  influxdb:
    container_name: influxdb
    extends:
      file: ../../services/database.yml
      service: influxdb
    labels:
      caddy: influxdb.home.bone6.com
      homepage.group: 工具
      homepage.href: https://influxdb.home.bone6.com
      homepage.icon: https://influxdb.home.bone6.com/gopher.svg

  telegraf:
    container_name: telegraf
    user: telegraf:969
    extends:
      file: ../../services/monitor.yml
      service: telegraf
